"""Add a column

Revision ID: 802724cce3f7
Revises: a53c1cb6ab39
Create Date: 2019-10-21 18:40:17.060738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802724cce3f7'
down_revision = 'a53c1cb6ab39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
